//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 01:08:28 PM MSK 
//


package its.ws.test;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the its.ws.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: its.ws.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDeviceRequest }
     * 
     */
    public GetDeviceRequest createGetDeviceRequest() {
        return new GetDeviceRequest();
    }

    /**
     * Create an instance of {@link GetAuthenticateRequest }
     * 
     */
    public GetAuthenticateRequest createGetAuthenticateRequest() {
        return new GetAuthenticateRequest();
    }

    /**
     * Create an instance of {@link GetAuthenticateResponse }
     * 
     */
    public GetAuthenticateResponse createGetAuthenticateResponse() {
        return new GetAuthenticateResponse();
    }

    /**
     * Create an instance of {@link GetCarsHeader }
     * 
     */
    public GetCarsHeader createGetCarsHeader() {
        return new GetCarsHeader();
    }

    /**
     * Create an instance of {@link GetCarsResponse }
     * 
     */
    public GetCarsResponse createGetCarsResponse() {
        return new GetCarsResponse();
    }

    /**
     * Create an instance of {@link Car }
     * 
     */
    public Car createCar() {
        return new Car();
    }

    /**
     * Create an instance of {@link GetDeviceHeader }
     * 
     */
    public GetDeviceHeader createGetDeviceHeader() {
        return new GetDeviceHeader();
    }

    /**
     * Create an instance of {@link GetCarsRequest }
     * 
     */
    public GetCarsRequest createGetCarsRequest() {
        return new GetCarsRequest();
    }

    /**
     * Create an instance of {@link GetEventsRequest }
     * 
     */
    public GetEventsRequest createGetEventsRequest() {
        return new GetEventsRequest();
    }

    /**
     * Create an instance of {@link GetDeviceResponse }
     * 
     */
    public GetDeviceResponse createGetDeviceResponse() {
        return new GetDeviceResponse();
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link GetEventsResponse }
     * 
     */
    public GetEventsResponse createGetEventsResponse() {
        return new GetEventsResponse();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link GetEventsHeader }
     * 
     */
    public GetEventsHeader createGetEventsHeader() {
        return new GetEventsHeader();
    }

}
