//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.18 at 03:02:42 AM MSK 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="event"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="idevent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="iddevice" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="coords" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="grz" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tsType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="maker" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="media" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "event", propOrder = {
    "idevent",
    "iddevice",
    "coords",
    "grz",
    "tsType",
    "speed",
    "maker",
    "model",
    "media"
})
public class Event {

    @XmlElement(required = true)
    protected String idevent;
    @XmlElement(required = true)
    protected String iddevice;
    @XmlElement(required = true)
    protected String coords;
    @XmlElement(required = true)
    protected String grz;
    @XmlElement(required = true)
    protected String tsType;
    @XmlElement(required = true)
    protected String speed;
    @XmlElement(required = true)
    protected String maker;
    @XmlElement(required = true)
    protected String model;
    @XmlElement(required = true)
    protected String media;

    /**
     * Gets the value of the idevent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdevent() {
        return idevent;
    }

    /**
     * Sets the value of the idevent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdevent(String value) {
        this.idevent = value;
    }

    /**
     * Gets the value of the iddevice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIddevice() {
        return iddevice;
    }

    /**
     * Sets the value of the iddevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIddevice(String value) {
        this.iddevice = value;
    }

    /**
     * Gets the value of the coords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoords() {
        return coords;
    }

    /**
     * Sets the value of the coords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoords(String value) {
        this.coords = value;
    }

    /**
     * Gets the value of the grz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrz() {
        return grz;
    }

    /**
     * Sets the value of the grz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrz(String value) {
        this.grz = value;
    }

    /**
     * Gets the value of the tsType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTsType() {
        return tsType;
    }

    /**
     * Sets the value of the tsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTsType(String value) {
        this.tsType = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeed(String value) {
        this.speed = value;
    }

    /**
     * Gets the value of the maker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaker() {
        return maker;
    }

    /**
     * Sets the value of the maker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaker(String value) {
        this.maker = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the media property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedia() {
        return media;
    }

    /**
     * Sets the value of the media property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedia(String value) {
        this.media = value;
    }

}
